features1<- read.table("features.txt")
features2<- gsub("[^A-Za-z0-9]", "", features1$V2)
features3<-gsub("fBodyBody*", "fbody", features2)
	x1<- read.table( "X_train.txt" )
 	x2<- read.table("X_test.txt" )
 	x<- rbind(x1,x2)
library(plyr)
library(dplyr)
features3<-t(features3)
names(x) = c(features3)
x2<-duplicated(names(x))
 x3<- x[, !x2]
x4<-select(x3, -contains("meanfreq"))
x5<-select(x4, contains("mean"))
x6<- select(x4, contains("std"))
x7<-cbind(x5, x6)
	y1<- read.table("y_train.txt")
	y2<- read.table("y_test.txt")
	y<- rbind(y1,y2)
	s1<- read.table("subject_train.txt")
 	s2<- read.table("subject_test.txt")
	s<- rbind(s1,s2)
 names(s) = c("subject_id")
 names(y) = c("activity_id")
	b2<-cbind(x7,s,y)
b5<- b2 %>% group_by(subject_id, activity_id) %>% summarise_each(funs(mean))
b5$activity_id = factor(b5$activity_id)
b5$activity_id <- revalue(b5$activity_id, c("1"="Walking", "2"="WalkingUpstairs", "3"="WalkingDownstairs", "4"="Sitting", "5"="Standing","6"="Laying"))
write.table(b5, file = "output.txt", row.name=FALSE)
